"""Excel and PDF export for invoice data."""

import io
from collections import defaultdict
from datetime import datetime


def _f(val) -> float:
    try:
        return float(val or 0)
    except (TypeError, ValueError):
        return 0.0


def generate_excel(invoices: list, user: dict, date_from: str = None, date_to: str = None) -> bytes:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment
    from openpyxl.utils import get_column_letter

    wb = Workbook()

    DARK_GREEN = "1B5E20"
    header_font = Font(bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(fill_type="solid", fgColor=DARK_GREEN)
    center = Alignment(horizontal="center", vertical="center")

    # ── Sheet 1: Invoice Summary ──
    ws = wb.active
    ws.title = "Invoice Summary"

    headers = [
        "Sr.", "Invoice Date", "Invoice No.", "Supplier Name", "Supplier GSTIN",
        "Taxable Amt (₹)", "CGST (₹)", "SGST (₹)", "IGST (₹)", "Total GST (₹)",
        "Grand Total (₹)", "ITC Eligible", "ITC Amount (₹)",
        "Status", "Filing Period", "Upload Source", "Uploaded On",
    ]
    ws.append(headers)
    for col_num in range(1, len(headers) + 1):
        cell = ws.cell(row=1, column=col_num)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = center
    ws.freeze_panes = "A2"

    alt_fill = PatternFill(fill_type="solid", fgColor="F0F7F0")
    for i, inv in enumerate(invoices, 1):
        gst = _f(inv.get("gst_amount"))
        row = [
            i,
            str(inv.get("date") or "")[:10],
            inv.get("invoice_number", ""),
            inv.get("supplier_name", ""),
            inv.get("supplier_gstin", ""),
            _f(inv.get("taxable_value")),
            _f(inv.get("cgst_amount")),
            _f(inv.get("sgst_amount")),
            _f(inv.get("igst_amount")),
            gst,
            _f(inv.get("total_amount")),
            "Yes" if inv.get("supplier_gstin") and len(str(inv.get("supplier_gstin", ""))) == 15 else "No",
            gst if inv.get("supplier_gstin") and len(str(inv.get("supplier_gstin", ""))) == 15 else 0,
            (inv.get("status") or "").upper(),
            inv.get("filing_period", ""),
            inv.get("upload_source", "app"),
            str(inv.get("created_at") or "")[:10],
        ]
        ws.append(row)
        if i % 2 == 0:
            for col in range(1, len(headers) + 1):
                ws.cell(row=i + 1, column=col).fill = alt_fill

    for col in ws.columns:
        max_len = max(len(str(cell.value or "")) for cell in col)
        ws.column_dimensions[get_column_letter(col[0].column)].width = min(max_len + 4, 40)
    ws.auto_filter.ref = ws.dimensions

    # ── Sheet 2: ITC Summary ──
    ws2 = wb.create_sheet("ITC Summary")
    itc_headers = ["Filing Period", "Total Invoices", "Total Amount (₹)", "ITC Eligible (₹)"]
    ws2.append(itc_headers)
    for col_num in range(1, len(itc_headers) + 1):
        ws2.cell(row=1, column=col_num).font = header_font
        ws2.cell(row=1, column=col_num).fill = header_fill

    period_data = defaultdict(lambda: {"count": 0, "amount": 0.0, "itc": 0.0})
    for inv in invoices:
        p = inv.get("filing_period") or "Unknown"
        period_data[p]["count"] += 1
        period_data[p]["amount"] += _f(inv.get("total_amount"))
        gstin = str(inv.get("supplier_gstin") or "")
        if len(gstin) == 15:
            period_data[p]["itc"] += _f(inv.get("gst_amount"))
    for period, d in sorted(period_data.items()):
        ws2.append([period, d["count"], round(d["amount"], 2), round(d["itc"], 2)])

    # ── Sheet 3: Flagged ──
    ws3 = wb.create_sheet("Flagged Invoices")
    ws3.append(["Invoice No.", "Supplier", "Amount (₹)", "Flag Reason", "Status", "Date"])
    for inv in invoices:
        if inv.get("is_duplicate") or inv.get("status") in ("error_gstin", "error_hsn", "anomalous"):
            ws3.append([
                inv.get("invoice_number", ""),
                inv.get("supplier_name", ""),
                _f(inv.get("total_amount")),
                "Duplicate" if inv.get("is_duplicate") else inv.get("status", ""),
                (inv.get("status") or ""),
                str(inv.get("created_at") or "")[:10],
            ])

    footer_row = len(invoices) + 3
    ws.cell(row=footer_row, column=1).value = (
        f"Generated by Hisably | User: {user.get('name', '')} | "
        f"Phone: {user.get('phone', '')} | "
        f"Period: {date_from or 'All'} to {date_to or 'All'} | "
        f"Total Records: {len(invoices)}"
    )

    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    return output.getvalue()


def generate_pdf(invoices: list, user: dict, date_from: str = None, date_to: str = None) -> bytes:
    from reportlab.lib import colors as rl_colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.units import inch
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.enums import TA_CENTER
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable

    DARK_GREEN = rl_colors.HexColor("#1B5E20")
    LIGHT_GREEN = rl_colors.HexColor("#F0F7F0")
    RED = rl_colors.HexColor("#C62828")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(A4), rightMargin=0.5 * inch, leftMargin=0.5 * inch,
                            topMargin=0.75 * inch, bottomMargin=0.75 * inch)

    title_style = ParagraphStyle("Title", fontSize=20, textColor=DARK_GREEN, fontName="Helvetica-Bold",
                                  alignment=TA_CENTER, spaceAfter=6)
    subtitle_style = ParagraphStyle("Subtitle", fontSize=11, textColor=rl_colors.gray,
                                     alignment=TA_CENTER, spaceAfter=4)
    section_style = ParagraphStyle("Section", fontSize=13, textColor=DARK_GREEN, fontName="Helvetica-Bold",
                                    spaceBefore=16, spaceAfter=8)

    story = []
    story.append(Paragraph("HISABLY", title_style))
    story.append(Paragraph("Invoice Register &amp; ITC Report", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=DARK_GREEN, spaceAfter=10))

    total_amt = sum(_f(i.get("total_amount")) for i in invoices)
    total_itc = sum(_f(i.get("gst_amount")) for i in invoices if len(str(i.get("supplier_gstin") or "")) == 15)

    info_data = [
        ["Account:", user.get("name", "N/A"), "Report Period:", f"{date_from or 'All'} to {date_to or 'All'}"],
        ["Phone:", user.get("phone", "N/A"), "Generated:", datetime.now().strftime("%d %b %Y %H:%M")],
        ["Total Invoices:", str(len(invoices)), "Total Amount:", f"Rs. {total_amt:,.2f}"],
        ["ITC Eligible:", f"Rs. {total_itc:,.2f}", "", ""],
    ]
    info_table = Table(info_data, colWidths=[1.5 * inch, 2.5 * inch, 1.5 * inch, 2.5 * inch])
    info_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (0, -1), DARK_GREEN),
        ("TEXTCOLOR", (2, 0), (2, -1), DARK_GREEN),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("GRID", (0, 0), (-1, -1), 0.5, rl_colors.lightgrey),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [LIGHT_GREEN, rl_colors.white]),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.3 * inch))

    story.append(Paragraph("Invoice Register", section_style))
    table_headers = ["Sr.", "Date", "Invoice No.", "Supplier", "GSTIN", "Grand Total", "GST", "Status"]
    col_widths = [0.35 * inch, 0.85 * inch, 1.3 * inch, 2.0 * inch, 1.5 * inch, 1.0 * inch, 0.9 * inch, 0.9 * inch]
    table_data = [table_headers]

    for i, inv in enumerate(invoices, 1):
        table_data.append([
            str(i),
            str(inv.get("date") or "")[:10],
            (inv.get("invoice_number") or "")[:18],
            (inv.get("supplier_name") or "")[:24],
            inv.get("supplier_gstin") or "",
            f"Rs.{_f(inv.get('total_amount')):,.0f}",
            f"Rs.{_f(inv.get('gst_amount')):,.0f}",
            (inv.get("status") or "").upper()[:12],
        ])

    inv_table = Table(table_data, colWidths=col_widths, repeatRows=1)
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), DARK_GREEN),
        ("TEXTCOLOR", (0, 0), (-1, 0), rl_colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [rl_colors.white, LIGHT_GREEN]),
        ("GRID", (0, 0), (-1, -1), 0.3, rl_colors.lightgrey),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("ALIGN", (5, 1), (6, -1), "RIGHT"),
    ]
    for row_idx, inv in enumerate(invoices, 1):
        if inv.get("status") in ("error_gstin", "error_hsn", "anomalous"):
            style_cmds.append(("BACKGROUND", (0, row_idx), (-1, row_idx), rl_colors.HexColor("#FFF3E0")))
    inv_table.setStyle(TableStyle(style_cmds))
    story.append(inv_table)

    story.append(Spacer(1, 0.2 * inch))
    story.append(HRFlowable(width="100%", thickness=1, color=rl_colors.lightgrey))
    story.append(Paragraph(
        f"Generated by Hisably | {datetime.now().strftime('%d %b %Y %H:%M')} | "
        f"Phone: {user.get('phone', 'N/A')} | This is a system-generated document.",
        ParagraphStyle("Footer", fontSize=7, textColor=rl_colors.grey, alignment=TA_CENTER, spaceBefore=4),
    ))

    doc.build(story)
    buf.seek(0)
    return buf.getvalue()
